### ISSUE TITLE
htmlhelp安装问题

### ISSUE THREAD

**Issue by ccbbaaa** [foyoux/docts#1]
我安装 htmlhelp的时候出现这个提示，自己从网上下了一个安装还是这个，感觉这个文件夹很奇怪...
![image](https://user-images.githubusercontent.com/89406155/130486747-55d1989e-6781-48a4-a28b-29212b87825b.png)

**Comment by lemisky** [comment]
没注意到这有个问题，不好意思呀，我还以为是自己开的。

你这应该是用户名中文的原因🙌
