### ISSUE TITLE
client问题

### ISSUE THREAD

**Issue by xcjc369** [foyoux/docts#3]
一直如下报错是怎么回事呀：
__init__() missing 1 required positional argument: 'client'

**Comment by lemisky** [comment]
请查看文档

```python
from docts import *

xlf_path = 'xlf_path.xlf'

# 使用示例方法
# todo(xlf_path)

# 运行完毕后, 会在xlf_path同目录下生成一个翻译好的文件, 则直接导入 Sisulizer

# 现在需要手动构造 client 参数，具体参考：https://github.com/foyoux/pygtrans
client = Translate(proxies={"https": "socks5://localhost:10808"})
doc = Doc(xlf_path, client)
# WordFilters对象的add_filter等方法直接转移到, Doc对象中
doc.add_filter(xxx_filter)

# 保存文件也无需使用 write_xl* 
doc.save_words()

# 需要导出忽略文件时
doc.save_ignores()

```

**Comment by xcjc369** [comment]
问题已解决，十分感谢您的帮助！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foyoux/docts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foyoux/docts] client问题 (Issue #3)





 
请查看文档
 from docts import * xlf_path = 'xlf_path.xlf' # 使用示例方法 # todo(xlf_path) # 运行完毕后, 会在xlf_path同目录下生成一个翻译好的文件, 则直接导入 Sisulizer # 现在需要手动构造 client 参数，具体参考：https://github.com/foyoux/pygtrans client = Translate(proxies={"https": "socks5://localhost:10808"}) doc = Doc(xlf_path, client) # WordFilters对象的add_filter等方法直接转移到, Doc对象中 doc.add_filter(xxx_filter) # 保存文件也无需使用 write_xl*  doc.save_words() # 需要导出忽略文件时 doc.save_ignores()
